/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthValidateLoginRouteImport } from './routes/_auth/validate-login'
import { Route as AuthCreateAccountRouteImport } from './routes/_auth/create-account'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthValidateLoginRoute = AuthValidateLoginRouteImport.update({
  id: '/validate-login',
  path: '/validate-login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCreateAccountRoute = AuthCreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/create-account': typeof AuthCreateAccountRoute
  '/validate-login': typeof AuthValidateLoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesByTo {
  '/create-account': typeof AuthCreateAccountRoute
  '/validate-login': typeof AuthValidateLoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/create-account': typeof AuthCreateAccountRoute
  '/_auth/validate-login': typeof AuthValidateLoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/create-account' | '/validate-login' | '/dashboard' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/create-account' | '/validate-login' | '/dashboard' | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/create-account'
    | '/_auth/validate-login'
    | '/_authenticated/dashboard'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/validate-login': {
      id: '/_auth/validate-login'
      path: '/validate-login'
      fullPath: '/validate-login'
      preLoaderRoute: typeof AuthValidateLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/create-account': {
      id: '/_auth/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof AuthCreateAccountRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCreateAccountRoute: typeof AuthCreateAccountRoute
  AuthValidateLoginRoute: typeof AuthValidateLoginRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCreateAccountRoute: AuthCreateAccountRoute,
  AuthValidateLoginRoute: AuthValidateLoginRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
